import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('PracticeLog')
export class PracticeSession {
    @autoGeneratedHashKey()
    user: string;

    @attribute()
    value: string;
}
