//import dynamo = require('aws-sdk/client-dynamodb-v2-node');

import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';


export const getUser = async (event: any={}) : Promise <any> => {
    console.log("Logging from getUser");
    console.log(event);
    return {
	statusCode: 200,
	body: "GetUser body"
    };
};

export const postUser = async (event: any={}) : Promise <any> => {
    console.log("Logging from postUser");
    console.log(event);
    return {
	statusCode: 200,
	body: "PostUser body"
    };
};
